project: 
  type: website
  output-dir: "docs/2023-2/"
  render:
    - index.qmd
    - programa1intro.qmd
    - programa2trabajo.qmd
    - programa3criterios.qmd
    - Tema-1.qmd
    - Tema-2.qmd
    - Tema-3.qmd
    - Tema-4.qmd
    - Tema-5.qmd

website:
  title: "Psicología Cognitiva"
  site-url: https://mmejia23.github.io/cognitiva/
  search: true
  page-navigation: true
  favicon: images/brain_256px.ico
  navbar:
    background: primary
    search: true
    left:
      - text: "Inicio"
        file: index.qmd
      - programa1intro.qmd
      - programa2trabajo.qmd
      - programa3criterios.qmd
      - sidebar:Title1
    
  sidebar:
    - id: Title1
      title: "📝 Temas"
      contents:
        - href: Tema-1.qmd
        - href: Tema-2.qmd
        - href: Tema-3.qmd
        - href: Tema-4.qmd
        - href: Tema-5.qmd
format: 
  html:
    theme: litera
    link-external-newwindow: true
    link-external-icon: true
    
lang: es
